debian/tests/tests-in-lxd: Work around snapd.seeded.service hanging

diff --git a/debian/tests/tests-in-lxd b/debian/tests/tests-in-lxd
--- a/debian/tests/tests-in-lxd
+++ b/debian/tests/tests-in-lxd
@@ -8,11 +8,26 @@ lxd init --auto
 
 IMAGE=autopkgtest/ubuntu/$(lsb_release -cs)/$(dpkg --print-architecture)
 
+# work around LP: #1878225 as fallback
+autopkgtest-build-lxd ubuntu-daily:$(lsb_release -cs) || \
+    patch /usr/bin/autopkgtest-build-lxd <<'EOF'
+@@ -70,6 +70,8 @@
+ 
+     sleep 5
+     if lxc exec "$CONTAINER" -- systemctl mask serial-getty@getty.service; then
++       lxc exec "$CONTAINER" -- systemctl mask snapd.service
++       lxc exec "$CONTAINER" -- systemctl mask snapd.seeded.service
+        lxc exec "$CONTAINER" -- reboot
+     fi
+ 
+EOF
+
+# help debugging if building lxd image still fails
 autopkgtest-build-lxd ubuntu-daily:$(lsb_release -cs) || \
     (lxc launch ubuntu-daily:$(lsb_release -cs) systemd-lxc
      sleep 60
      lxc exec systemd-lxc systemctl is-system-running || (lxc exec systemd-lxc -- systemctl list-units --failed ; lxc exec systemd-lxc systemctl list-jobs ; lxc exec systemd-lxc -- journalctl -a)
-     exit 77) # LP: #1878225
+     exit 1)
 
 # push local apt configuration to match pinning
 lxc launch $IMAGE systemd-lxc
