d/t/upstream: always cleanup after (and before) each test
run the 'clean' target before setup/run, to match the upstream
'all' target's behavior; also the clean (again) target must be
run separately, as the failure of setup or run will stop make,
and cleanup won't be done if called in the same make line.

diff --git a/debian/tests/upstream b/debian/tests/upstream
--- a/debian/tests/upstream
+++ b/debian/tests/upstream
@@ -36,7 +36,7 @@ for t in test/TEST*; do
     echo "$BLACKLIST" | grep -q "$(basename $t)" && continue
     echo "========== `basename $t` =========="
     rm -rf /var/tmp/systemd-test.*
-    if ! make -C $t setup run clean; then
+    if ! make -C $t clean setup run; then
         for j in /var/tmp/systemd-test.*/journal/*; do
             [ -e "$j" ] || continue
             # keep the entire journal in artifacts, in case one needs the debug messages
@@ -47,6 +47,8 @@ for t in test/TEST*; do
         FAILED="$FAILED $t"
     fi
     echo
+    # always cleanup each test run
+    make -C $t clean-again
 done
 
 if [ -n "$FAILED" ]; then
