systemd.postinst: Don't fail on an existing dynamic systemd-timesync user
Some systemd versions have DynamicUser=yes in systemd-timesyncd.service.
adduser does not consider these high UIDs as system user and fails,
which caused package installation failures.

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -107,8 +107,9 @@ if dpkg --compare-versions "$2" lt-nl "239-6"; then
     done
 fi
 
+# don't fail with DynamicUser= while timesyncd is running
 adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Time Synchronization" systemd-timesync
+    --gecos "systemd Time Synchronization" systemd-timesync || true
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Network Management" systemd-network
 adduser --quiet --system --group --no-create-home --home /run/systemd \
