debian/systemd.postint: do not daemon re-exec if we could hit LP: #2013543
Unfortunately, there is not a simple way to check all cases in which
the running systemd will hit this bug when re-executing. To be safe, do
not try re-exec on upgrades from affected versions, and instead indicate
that a reboot is required.

Gbp-Dch: Short

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -80,7 +80,23 @@ systemd-tmpfiles --create || :
 
 # skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
 if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
-    _systemctl daemon-reexec || true
+    # LP: #2013543 - the systemd cmdline can get mangled depending on the
+    # contents of /proc/cmdline, which causes systemd to fail to deserialize
+    # it's previous state on daemon-reexec. This means that for upgrades from
+    # affected versions, we need a reboot and cannot re-exec here, else the
+    # bug could be triggered.
+    if dpkg --compare-versions "$2" lt "249.11-0ubuntu3.10~" ||
+        dpkg --compare-versions "$2" eq "252.5-2ubuntu3" ||
+        dpkg --compare-versions "$2" eq "253.5-1ubuntu1"; then
+        if ! grep -Fqsx systemd /run/reboot-required.pkgs; then
+            echo systemd >> /run/reboot-required.pkgs || true
+        fi
+
+        # Reload to avoid warnings when restarting services below
+        _systemctl daemon-reload || true
+    else
+        _systemctl daemon-reexec || true
+    fi
     # do not restart logind
     # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919509
     if dpkg --compare-versions "$2" lt-nl "246.2-2~"; then
