debian/systemd-resolved.postinst: ignore cp failure (LP: #2047975)
In come cases, copying /etc/resolv.conf to /run/systemd/resolve/stub-resolv.conf
will fail, despite the checks that happen beforehand. In particular,
this can happen if a user disabled the stub-resolver, and in doing so,
made /etc/resolv.conf a symlink to /run/systemd/resolve/resolv.conf.
This is unnecessary because systemd-resolved will make stub-resolv.conf
a symlink to resolv.conf if DNSStubListener=no. In these cases, it is
safe to just ignore the cp because it is unnecssary to begin with.

Gbp-Dch: Short

diff --git a/debian/systemd-resolved.postinst b/debian/systemd-resolved.postinst
--- a/debian/systemd-resolved.postinst
+++ b/debian/systemd-resolved.postinst
@@ -28,7 +28,7 @@ if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 251.4-2; then
         echo "Converting /etc/resolv.conf to a symlink to /run/systemd/resolve/stub-resolv.conf..."
         mkdir -p "${DPKG_ROOT}/run/systemd/resolve"
         if [ -f "${DPKG_ROOT}/etc/resolv.conf" ]; then
-            cp "${DPKG_ROOT}/etc/resolv.conf" "${DPKG_ROOT}/run/systemd/resolve/stub-resolv.conf"
+            cp "${DPKG_ROOT}/etc/resolv.conf" "${DPKG_ROOT}/run/systemd/resolve/stub-resolv.conf" || echo "Cannot copy /etc/resolv.conf to /run/systemd/resolve/stub-resolv.conf"
             mv "${DPKG_ROOT}/etc/resolv.conf" "${DPKG_ROOT}/etc/.resolv.conf.systemd-resolved.bak" || echo "Cannot take a backup of /etc/resolv.conf."
         fi
         ln -sf ../run/systemd/resolve/stub-resolv.conf "${DPKG_ROOT}/etc/resolv.conf" || echo "Cannot install symlink from /etc/resolv.conf to ../run/systemd/resolve/stub-resolv.conf"
